category:
  class: sfPropelORMRouteCollection
  options:
    model:                category
    module:               category
    prefix_path:          /category
    column:               id
    with_wildcard_routes: true

board:
  class: sfPropelORMRouteCollection
  options:
    model:                board
    module:               board
    prefix_path:          /board
    column:               id
    with_wildcard_routes: true

sf_guard_user_group:
  class: sfPropelORMRouteCollection
  options:
    model:                sfGuardUserGroup
    module:               sf_guard_user_group
    prefix_path:          /sf_guard_user_group
    column:               user_id
    with_wildcard_routes: true

sf_guard_group:
  class: sfPropelORMRouteCollection
  options:
    model:                sfGuardGroup
    module:               sf_guard_group
    prefix_path:          /sf_guard_group
    column:               id
    with_wildcard_routes: true

sf_guard_permission:
  class: sfPropelORMRouteCollection
  options:
    model:                sfGuardPermission
    module:               sf_guard_permission
    prefix_path:          /sf_guard_permission
    column:               id
    with_wildcard_routes: true

sf_guard_user_permission:
  class: sfPropelORMRouteCollection
  options:
    model:                sfGuardUserPermission
    module:               sf_guard_user_permission
    prefix_path:          /sf_guard_user_permission
    column:               user_id
    with_wildcard_routes: true

sf_guard_user:
  class: sfPropelORMRouteCollection
  options:
    model:                sfGuardUser
    module:               sf_guard_user
    prefix_path:          /sf_guard_user
    column:               id
    with_wildcard_routes: true

scene:
  class: sfPropelORMRouteCollection
  options:
    model:                Scene
    module:               scene
    prefix_path:          /scene
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: sfAdminDash, action: dashboard }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }