# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
  facebook:
    page: 'http://www.facebook.com/pages/ClipClockcom/286585384701717'
  sfCombinePlugin:
    enabled:        false
    timestamp:
      enabled:      false
  kiss:
    key: '1aa5caf92bb95c578572665690bb8908c08fac30'
  registration:
    confirm: true
    invites: false
    robot_email:           "feedback@clipclock.com"
    robot_name:            "ClipClock.com"
  boards:
    voting: false
  sf_guard_plugin:
   profile_class:      sfGuardUserProfile
   profile_field_name: sf_guard_user_id
  melody:
    create_user: true               # to create a user for all melodies
    use_profile: true
    remember_user: true
    redirect_register: @user_register
    facebook:                       #http://viddii.dev/frontend_dev.php/access/facebook
      key: 365665100128423
      secret: 222bb675913bc944dc8a56252bc415ac
      callback: @user_register_welcome
      scope:
        - email
#        - user_about_me
#        - user_activities
#        - user_birthday
#        - user_education_history
#        - user_events
#        - user_groups
#        - user_interests
#        - user_likes
#        - user_notes
#        - user_photos
#        - user_relationships
#        - user_status
#        - user_videos
#        - user_work_history
#        - user_location
#        - friends_about_me
#        - friends_activities
#        - friends_birthday
#        - friends_education_history
#        - friends_events
#        - friends_groups
#        - friends_interests
#        - friends_likes
#        - friends_notes
#        - friends_photos
#        - friends_status
#        - friends_videos
#        - friends_work_history
#        - friends_location
#        - read_friendlists
#        - read_stream
#        - publish_stream
        - publish_actions
                      #optionnal - http://developers.facebook.com/docs/authentication/permissions
                                        # needed to create an user based on his email_address
      user:
        username:                   # the name of a field of sfGuardUser
          call: me                  # api call
          path: id                  # path could be user.object.email for example to retrieve the right inforamtion
          prefix: Facebook_
        email:
          call: me
          path: email
          key: true                 # it's a key to retrieve user from other services based on this information# if no field is a key all are keys by default.
        first_name:
          call: me
          path: first_name
        last_name:
          call: me
          path: last_name
        nick:
          call: me
          path: username
        nick:
          call: me
          path: username
      aliases:
        nickname: 'me?fields=name'
        id: 'me?fields=id'
        link: 'me?fields=link'
        photo: 'me?fields=picture&type=large'
        avatar: 'me?fields=picture&type=square'
        gender: 'me?fields=gender'
        country: 'me?fields=location'

prod:
  melody:
    facebook:                       #http://dev.viddii.com/frontend_dev.php/access/facebook
      key: 398827136799487
      secret: 6db3eb2142819ee6e5f87ed9b97af946
  kiss:
    key: '572923c43021801f02ed554e056687be886506ba'
  sfCombinePlugin:
    enabled:        true
    timestamp:
      enabled:      true