# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

### BOARD ###

board:
  url:   /:username_slug/board/:id
  class: sfPropelRoute
  param: { module: board, action: show }
  options: { model: Board, type: object }
  requirements:
    id: \d+

### STICKER AJAX ###

sticker_scene_change:
  url:   /scene/sticker/:scene_id
  param: { module: board, action: showSceneAjax }
  requirements:
    scene_id: \d+

### SCENE ###

scene:
  url:   /:username_slug/board/:board_id/scene/:id
  class: sfPropelRoute
  param: { module: scene, action: show }
  options: { model: Scene, type: object }
  requirements:
    board_id: \d+
    id: \d+

scene_unrepin:
  url: /scene/unrepin
  param: { module: scene, action: unrepin }

scene_repin:
  url: /scene/repin
  param: { module: scene, action: repin }

scene_post:
  url: /post/scene
  param: { module: scene, action: postScene }

scene_post_comment:
  url: /post/scene/comment
  param: { module: scene, action: postComment }

scene_change_liked_state:
  url: /change/scene/like/state
  param: { module: scene, action: toggleFBLikeState }

### STICKER AJAX ###

scene_change:
  url:   /scene/:scene_id
  param: { module: scene, action: showSceneAjax }
  requirements:
    scene_id: \d+

### USER ###

user:
  url:   /profile/:nick
  class: sfPropelRoute
  param: { module: user, action: show }
  options: { model: sfGuardUserProfile, type: object }

### MELODY CALLBACKS ###

user_register:
  url:   /user/register
  param: { module: user, action: register }

user_register_welcome:
  url:   /user/welcome
  param: { module: user, action: welcome }

### MELODY ROUTINE ###

connect_fb:
  url:   /connect_fb
  param: { module: user, action: connect }

callback_fb:
  url:   /callback_fb
  param: { module: user, action: facebook}

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

### ADD NEW CLIP ###

preview_new_clip:
  url:  /preview
  param: { module: static, action: previewNew}

new_clip_scene_post:
  url:  /preview/create
  param: { module: static, action: newClipPostScene}