# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

user_register:
  url:   /user/register
  param: { module: user, action: register }

user_register_welcome:
  url:   /user/welcome
  param: { module: user, action: welcome }

connect_fb:
  url:   /connect_fb
  param: { module: user, action: connect }

callback_fb:
  url:   /callback_fb
  param: { module: user, action: facebook}

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }