# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

### BOARD ###

board:
  url:   /:username_slug/board/:id
  class: sfPropelRoute
  param: { module: board, action: show }
  options: { model: Board, type: object }
  requirements:
    id: \d+

### STICKER AJAX ###

sticker_scene_change:
  url:   /scene/sticker/:scene_id
  param: { module: board, action: showSceneAjax }
  requirements:
    scene_id: \d+

### SCENE ###

scene:
  url:   /:username_slug/board/:board_id/scene/:id
  class: sfPropelRoute
  param: { module: scene, action: show }
  options: { model: Scene, type: object }
  requirements:
    board_id: \d+
    id: \d+

### STICKER AJAX ###

scene_change:
  url:   /scene/:scene_id
  param: { module: scene, action: showSceneAjax }
  requirements:
    scene_id: \d+

### MELODY CALLBACKS ###

user_register:
  url:   /user/register
  param: { module: user, action: register }

user_register_welcome:
  url:   /user/welcome
  param: { module: user, action: welcome }

### MELODY ROUTINE ###

connect_fb:
  url:   /connect_fb
  param: { module: user, action: connect }

callback_fb:
  url:   /callback_fb
  param: { module: user, action: facebook}

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }