# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    cache:                  true
    logging_enabled:        false
    etag:                   false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              false
    cache:                  true
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .actions:
    error_404_module:       static
    error_404_action:       error404
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            false

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    jquery_core: jquery-1.7.1.min.js

    secure_module:          sfGuardAuth
    secure_action:          secure

    # Enable the database manager
    use_database:           true
    enabled_modules:        [default, sfGuardGroup, sfGuardUser, sfCombine, sfGuardAuth, sfGuardPermission, sfMelody, sfPropelOAuthPlugin]
    standard_helpers:       [Partial, Cache, Slug, jQuery, Text, sfCombine, Comment, Navigation, Url]
    check_lock: off
