# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:         'ClipClock.com - great video moments publishing, commenting, and searching in social environment'
    description:   'ClipClock.com - publish, comment, share and search your great video scenes and best moments. Take any video from YouTube, Vimeo, Dailymotion or other video hostings, add a time tag to the right moment on the video timeline and share your clip on Facebook or other social platforms. You would gift your friends extra life time, they could spend on the important things rather than scanning the video for the relevant content.'
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [style.css?2, cusel.css]

  javascripts:    [swfobject.js, clipEmbed.js?1, ajaxCallbacks.js?1, fb.js, repin.js, follow.js, cusel.js, source.js?1, jquery.wookmark.min.js,  jquery.infinitescroll.js, follow.js, jquery.easing.1.3.js, jquery.ui.totop.js, jquery-ui-1.8.18.custom.min.js]

  has_layout:     true
  layout:         layout
