# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        'ClipClock.com'
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [style.css, cusel.css]

  javascripts:    [swfobject.js, clipEmbed.js, ajaxCallbacks.js, fb.js, repin.js, follow.js, cusel.js, source.js, jquery.wookmark.min.js,  jquery.infinitescroll.js, follow.js, jquery.easing.1.3.js, jquery.ui.totop.js, jquery-ui-1.8.18.custom.min.js]

  has_layout:     true
  layout:         layout
