generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardGroup
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              sfGuardGroup
    plural:                sfGuardGroups
    route_prefix:          sf_guard_group
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   nothing

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
