generator:
  class: sfPropelGenerator
  param:
    model_class:           board
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              board
    plural:                boards
    route_prefix:          board
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   nothing

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:
        class: BackendBoardForm
      edit:    ~
      new:     ~
