generator:
  class: sfPropelGenerator
  param:
    model_class:           board
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              board
    plural:                boards
    route_prefix:          board
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   nothing

    config:
      actions: ~
      fields:
        name: {label: 'Название'}
        sf_guard_user_profile_id: {label: 'Пользователь'}
        board_refs_category_list: {label: 'Категория'}
      list:
        display: [id, name, sf_guard_user_profile_id_backend]
        sort: [id, desc]
        fields:
          sf_guard_user_profile_id_backend: {label: 'Пользователь'}
      filter:  ~
      form:
        class: BackendBoardForm
      edit:    ~
      new:     ~
