<?php



/**
 * Skeleton subclass for representing a row from the 'board_follower' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Thu Feb 23 12:39:28 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BoardFollower extends BaseBoardFollower {

} // BoardFollower
