<?php



/**
 * Skeleton subclass for performing query and update operations on the 'board_follower' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Thu Feb 23 12:39:28 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BoardFollowerPeer extends BaseBoardFollowerPeer {

    protected static function buildFollowerCriteria($board_id, $user_id, $insert = false)
    {
        $c = new Criteria();
        $c->add(self::BOARD_ID, $board_id);
        $c->add(self::FOLLOWER_SF_GUARD_USER_PROFILE_ID, $user_id);
		if($insert)
		{
			$c->add(self::CREATED_AT, date('Y-m-d H:i:s', time()-7*24*3600));
		}

        return $c;
    }

    public static function isBoardFollowedByUser($board_id, $user_id)
    {
        return self::doCount(self::buildFollowerCriteria($board_id, $user_id));
    }

    public static function followBoardByUser($board_id, $user_id)
    {
        try {
            self::doInsert(self::buildFollowerCriteria($board_id, $user_id, true));
        } catch (Exception $e) {
            return false;
        }

        return true;
    }

    public static function unfollowBoardByUser($board_id, $user_id)
    {
        try {
            self::doDelete(self::buildFollowerCriteria($board_id, $user_id));
        } catch (Exception $e) {
            return false;
        }

        return true;
    }

	public static function retrieveIdByFollowerForFollowing($user_id, $following_id)
	{
		$c = new Criteria();
		$c->add(self::FOLLOWER_SF_GUARD_USER_PROFILE_ID, $user_id);
		$c->add(BoardPeer::SF_GUARD_USER_PROFILE_ID, $following_id);
		$c->addJoin(BoardPeer::ID, self::BOARD_ID, Criteria::INNER_JOIN);
		$c->clearSelectColumns();
		$c->addSelectColumn(self::BOARD_ID . ' as board_id');

		return BasePeer::doSelect($c)->fetchAll(PDO::FETCH_ASSOC);
	}
} // BoardFollowerPeer
