<?php



/**
 * Skeleton subclass for representing a row from the 'board' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  6 03:06:04 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Board extends BaseBoard {

    public function __toString()
    {
        return $this->getName();
    }

	public function getSfGuardUserProfileIdBackend()
	{
		return  $this->getSfGuardUserProfileId() . '/' . $this->getSfGuardUserProfile()->getFullName();
	}

	public function getUsernameSlug()
	{
		return slugify($this->getSfGuardUserProfile()->getNick());
	}

	public function delete(PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ScenePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			SceneQuery::create()->filterByBoardId($this->id)->delete($con);
			BoardFollowerQuery::create()->filterByBoardId($this->id)->delete($con);
			HistoryQuery::create()->filterByBoardId($this->id)->delete($con);
			parent::delete($con);
			$con->commit();
		}
		catch(Exception $e)
		{
			$con->rollBack();
			throw $e;
		}
	}
} // Board
