<?php



/**
 * Skeleton subclass for performing query and update operations on the 'board_follower' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Thu Feb 23 12:39:28 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BoardFollowerPeer extends BaseBoardFollowerPeer {

    protected static function buildFollowerCriteria($board_id, $user_id)
    {
        $c = new Criteria();
        $c->add(self::BOARD_ID, $board_id);
        $c->add(self::FOLLOWER_SF_GUARD_USER_PROFILE_ID, $user_id);

        return $c;
    }

    public static function isBoardFollowedByUser($board_id, $user_id)
    {
        return self::doCount(self::buildFollowerCriteria($board_id, $user_id));
    }

    public static function followBoardByUser($board_id, $user_id)
    {
        try {
            self::doInsert(self::buildFollowerCriteria($board_id, $user_id));
        } catch (Exception $e) {
            return false;
        }

        return true;
    }

    public static function unfollowBoardByUser($board_id, $user_id)
    {
        try {
            self::doDelete(self::buildFollowerCriteria($board_id, $user_id));
        } catch (Exception $e) {
            return false;
        }

        return true;
    }
} // BoardFollowerPeer
