<?php



/**
 * Skeleton subclass for performing query and update operations on the 'board' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  6 03:06:04 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BoardPeer extends BaseBoardPeer {

	public static function doSelectByUserId($user_id)
	{
		$c = new Criteria();
		$c->add(BoardPeer::SF_GUARD_USER_PROFILE_ID, $user_id);

		return self::doSelect($c);
	}
} // BoardPeer
