<?php



/**
 * Skeleton subclass for representing a row from the 'board_refs_category' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Wed Mar 21 20:06:01 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class BoardRefsCategory extends BaseBoardRefsCategory {

} // BoardRefsCategory
