<?php



/**
 * Skeleton subclass for performing query and update operations on the 'clip_follower' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Thu Feb 23 12:39:28 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ClipFollowerPeer extends BaseClipFollowerPeer {

    protected static function buildFollowerCriteria($clip_id, $user_id, $insert = false)
    {
        $c = new Criteria();
        $c->add(self::CLIP_ID, $clip_id);
        $c->add(self::FOLLOWER_SF_GUARD_USER_PROFILE_ID, $user_id);
		if($insert)
		{
			$c->add(self::CREATED_AT, date('Y-m-d H:i:s', time()-7*24*3600));
		}

        return $c;
    }

    public static function isClipFollowedByUser($clip_id, $user_id)
    {
        return self::doCount(self::buildFollowerCriteria($clip_id, $user_id));
    }

    public static function followClipByUser($clip_id, $user_id)
    {
        try {
            self::doInsert(self::buildFollowerCriteria($clip_id, $user_id, true));
        } catch (Exception $e) {
            return false;
        }

        return true;
    }

    public static function unfollowClipByUser($clip_id, $user_id)
    {
        try {
            self::doDelete(self::buildFollowerCriteria($clip_id, $user_id));
        } catch (Exception $e) {
            return false;
        }

        return true;
    }

	public static function retrieveIdByFollower($user_id)
	{
		$c = new Criteria();
		$c->add(self::FOLLOWER_SF_GUARD_USER_PROFILE_ID, $user_id);
		$c->clearSelectColumns();
		$c->addSelectColumn(self::CLIP_ID . ' as clip_id');
		$c->addSelectColumn(self::CREATED_AT . ' as created_at');
		$c->setLimit(1);

		return BasePeer::doSelect($c)->fetch(PDO::FETCH_ASSOC);
	}
} // ClipFollowerPeer
