<?php



/**
 * Skeleton subclass for performing query and update operations on the 'clip_social_info' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Thu Apr 19 18:01:53 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ClipSocialInfoPeer extends BaseClipSocialInfoPeer {

	public static function retrieveByReclipId($reclip_id)
	{
		$c = new Criteria();

		$c->addJoin(self::ID, ClipPeer::CLIP_SOCIAL_INFO_ID, Criteria::INNER_JOIN);
		$c->addJoin(ClipPeer::ID, ReclipPeer::CLIP_ID, Criteria::INNER_JOIN);
		$c->add(ReclipPeer::ID, $reclip_id);
		$c->setLimit(1);

		return current(self::doSelectJoinExtUser($c));
	}
} // ClipSocialInfoPeer
