<?php



/**
 * Skeleton subclass for performing query and update operations on the 'clip' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  6 03:06:04 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ClipPeer extends BaseClipPeer {

	public static function retrieveBySceneTimeId($scene_time_id)
	{
		$c = new Criteria();

		$c->clearSelectColumns();

		$c->addJoin(self::ID, SceneTimePeer::CLIP_ID, Criteria::INNER_JOIN);
		$c->add(SceneTimePeer::ID, $scene_time_id);
		$c->setLimit(1);

		return current(self::doSelectJoinSource($c));
	}
} // ClipPeer
