<?php



/**
 * Skeleton subclass for performing query and update operations on the 'follower_user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Sat Feb 18 17:27:34 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class FollowerUserPeer extends BaseFollowerUserPeer {

	public static function countFollowersAndFollowingByUserId($user_id)
	{
		$c = new Criteria();
		$c->clearSelectColumns();
		$c->addSelectColumn(self::FOLLOWER_SF_GUARD_USER_PROFILE_ID.' as count');
		$c->add(self::FOLLOWING_SF_GUARD_USER_PROFILE_ID, $user_id);
		$followers_count = BasePeer::doCount($c)->fetch(PDO::FETCH_ASSOC);

		$c = new Criteria();
		$c->clearSelectColumns();
		$c->addSelectColumn(self::FOLLOWING_SF_GUARD_USER_PROFILE_ID.' as count');
		$c->add(self::FOLLOWER_SF_GUARD_USER_PROFILE_ID, $user_id);
		$followings_count = BasePeer::doCount($c)->fetch(PDO::FETCH_ASSOC);

		return array('followers_count' => $followers_count['count'], 'followings_count' => $followings_count['count']);
	}
} // FollowerUserPeer
