<?php



/**
 * Skeleton subclass for performing query and update operations on the 'invites' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Fri Mar 23 20:01:07 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class InvitesQuery extends BaseInvitesQuery {

} // InvitesQuery
