<?php



/**
 * Skeleton subclass for representing a row from the 'reclip' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Wed Feb 29 21:25:06 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Reclip extends BaseReclip {

	public function delete(PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ScenePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			foreach(SceneTimeQuery::create()->findByReclipId($this->id) as $scene_time)
			{
				$scene_time->delete($con);
			}
			parent::delete($con);
			$con->commit();
		}
		catch(Exception $e)
		{
			$con->rollBack();
			throw $e;
		}
	}
} // Reclip
