<?php



/**
 * Skeleton subclass for performing query and update operations on the 'scene_archive' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Mon Mar 19 15:30:57 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SceneArchiveQuery extends BaseSceneArchiveQuery {

} // SceneArchiveQuery
