<?php



/**
 * Skeleton subclass for performing query and update operations on the 'comment_rating_votes' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Tue Mar  6 14:20:31 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SceneCommentRatingVotesPeer extends BaseSceneCommentRatingVotesPeer {

	public static function retrieveForSceneTimeId($scene_time_id, $user_id)
	{
		$result = array();
		if($user_id > 0)
		{
			$c = new Criteria();
			$c->setPrimaryTableName(self::TABLE_NAME);
			$c->addMultipleJoin(array(
				array(self::COMMENT_ID, SceneCommentPeer::ID),
				array(SceneCommentPeer::SCENE_TIME_ID, $scene_time_id),
				array(self::SF_GUARD_USER_PROFILE_ID, $user_id)
			), Criteria::INNER_JOIN);
			$c->clearSelectColumns();
			$c->addSelectColumn(self::COMMENT_ID);

			$result = BasePeer::doSelect($c)->fetchAll(PDO::FETCH_ASSOC);
		}
		$array = array();
		foreach($result as $comment)
		{
			$array[$comment['comment_id']] = true;
		}

		return $array;
	}
} // SceneCommentRatingVotesPeer
