<?php



/**
 * Skeleton subclass for representing a row from the 'comment_rating_votes' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4 on:
 *
 * Tue Mar  6 14:20:31 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SceneCommentRatingVotes extends BaseSceneCommentRatingVotes {

} // SceneCommentRatingVotes
