<?php



/**
 * Skeleton subclass for performing query and update operations on the 'comment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb 13 15:38:22 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SceneCommentPeer extends BaseSceneCommentPeer {
	public static function retrieveShortBySceneId($scene_id, $max_limit = 50)
	{
		$c = new Criteria();

		$c->addJoin(self::SCENE_TIME_ID, ScenePeer::SCENE_TIME_ID, Criteria::INNER_JOIN);
		$c->add(ScenePeer::ID, $scene_id);
		$c->addAscendingOrderByColumn(self::CREATED_AT);
		$c->setLimit($max_limit);

		return self::doSelectJoinSfGuardUserProfile($c);
	}

	public static function retrieveFullBySceneTimeId($scene_time_id)
	{
		$c = new Criteria();

		$c->add(self::SCENE_TIME_ID, $scene_time_id);
		$c->addDescendingOrderByColumn(self::CREATED_AT);

		return self::doSelectJoinSfGuardUserProfile($c);
	}
} // SceneCommentPeer
