<?php



/**
 * Skeleton subclass for representing a row from the 'scene' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  6 03:06:04 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class Scene extends BaseScene {

	public function getUsernameSlug()
	{
		return $this->getSfGuardUserProfile()->getNick();
	}

	public function __toString()
	{
		return $this->getText();
	}

	public function getSceneTimeBackend()
	{
		return $this->getSceneTime()->getSceneTime();
	}

	public function getBoardBackend()
	{
		return $this->getBoardId() . '/' . $this->getBoard();
	}

	public function getSfGuardUserProfileIdBackend()
	{
		return  $this->getSfGuardUserProfileId() . '/' . $this->getSfGuardUserProfile()->getFullName();
	}

	public function getTextShort()
	{
		return substr($this->getText(), 0, 40).'..';
	}

	public function getHide()
	{
		return $this->getSceneTime()->getReclip()->getClip()->getHide();
	}

	public function delete(PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ScenePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			SceneQuery::create()->filterByRepinOriginSceneId($this->id)->delete($con);//TODO: foreach
			SceneLikeQuery::create()->filterBySceneId($this->id)->delete($con);
			SceneRepinQuery::create()->filterBySceneId($this->id)->delete($con);
			HistoryQuery::create()->filterBySceneId($this->id)->delete($con);
			$c14n_id = $this->getSceneTime()->getReclip()->getClipId().$this->getSceneTime()->getSceneTime();
			ImagePreview::deleteAllImages($c14n_id);

			parent::delete($con);
			$con->commit();
		}
		catch(Exception $e)
		{
			$con->rollBack();
			throw $e;
		}
	}
} // Scene
