<?php



/**
 * Skeleton subclass for representing a row from the 'comment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb 13 15:38:22 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SceneComment extends BaseSceneComment {

	public function __toString()
	{
		return $this->getText();
	}

	public function save(PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(SceneCommentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$con->beginTransaction();
		$affected_rows = parent::save($con);
		try
		{
			SceneTimePeer::recountUniqueComments($this->getSceneTimeId());
			$con->commit();
			return $affected_rows;
		} catch (Exception $e) {
			$con->rollBack();
		}
	}

	public function delete(PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ScenePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			foreach(SceneCommentQuery::create()->findByReplyToCommentId($this->id) as $replied_scene_comment)
			{
				$replied_scene_comment->delete($con);
			}

			foreach(SceneCommentRatingVotesQuery::create()->findByCommentId($this->id) as $rating_scene_comment)
			{
				$rating_scene_comment->delete($con);
			}

			foreach(HistoryQuery::create()->findByCommentId($this->id) as $history_comment)
			{
				$history_comment->delete($con);
			}
			parent::delete($con);
			$con->commit();
		}
		catch(Exception $e)
		{
			$con->rollBack();
			throw $e;
		}
	}
}