<?php



/**
 * Skeleton subclass for representing a row from the 'scene_time' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb 13 17:54:27 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SceneTime extends BaseSceneTime {

    public function __toString()
    {
        return date('i:s', mktime(0, 0, $this->getSceneTime()));
    }
} // SceneTime
