<?php



/**
 * Skeleton subclass for representing a row from the 'scene_time' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb 13 17:54:27 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SceneTime extends BaseSceneTime {

    public function __toString()
    {
        return date('i:s', mktime(0, 0, $this->getSceneTime()));
    }

	public function delete(PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(ScenePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			foreach(SceneQuery::create()->findBySceneTimeId($this->id) as $scene)
			{
				$scene->delete($con);
			}

			foreach(SceneCommentQuery::create()->findBySceneTimeId($this->id) as $scene_comment)
			{
				$scene_comment->delete($con);
			}
			parent::delete($con);
			$con->commit();
		}
		catch(Exception $e)
		{
			$con->rollBack();
			throw $e;
		}
	}
} // SceneTime
