<?php



/**
 * Skeleton subclass for performing query and update operations on the 'scene_like' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  6 03:06:04 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SceneLikePeer extends BaseSceneLikePeer {

    public static function getCountByUserId($user_id)
    {
        $c = new Criteria();
        $c->addJoin(self::SCENE_ID, ScenePeer::ID, Criteria::INNER_JOIN);
        $c->add(ScenePeer::SF_GUARD_USER_PROFILE_ID, $user_id);
        return self::doCount($c);
    }

	public static function retrieveIdsBySceneId($scene_id)
	{
		$c = new Criteria();
		$c->add(self::SCENE_ID, $scene_id);
		$c->clearSelectColumns();
		$c->addSelectColumn(self::LIKE_SF_GUARD_USER_PROFILE_ID);
		$c->addDescendingOrderByColumn(self::CREATED_AT);
		$c->setLimit(12);

		return BasePeer::doSelect($c)->fetchAll(PDO::FETCH_ASSOC);
	}

    public static function toggleBySceneIdAndUserIdByState($scene_id, $user_id, $state)
    {
        $c = new Criteria();;
        $c->add(self::LIKE_SF_GUARD_USER_PROFILE_ID, $user_id);
        $c->add(self::SCENE_ID, $scene_id);

        if ($state) {

            try {
                self::doInsert($c);
            } catch (Exception $e) {
                return false; // already isseted
            }

            return true; // new record
        }

        return self::doDelete($c); // if nothing to delete = 0, else 1

    }

} // SceneLikePeer
