<?php



/**
 * Skeleton subclass for performing query and update operations on the 'scene' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  6 03:06:04 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ScenePeer extends BaseScenePeer {

	public static function retrieveClipsIdsByBoard(Board $board, Criteria $c = null)
	{
		$c = !$c ? new Criteria() : $c;
		$c->add(self::BOARD_ID, $board->getId());

		$c->addJoin(self::ID, SceneCommentPeer::SCENE_ID, Criteria::INNER_JOIN);

		$c->clearSelectColumns();
		$c->addSelectColumn(self::CLIP_ID);

		$c->addGroupByColumn(self::CLIP_ID);
		$c->addDescendingOrderByColumn('count('. SceneCommentPeer::ID .')');
		return BasePeer::doSelect($c)->fetchAll(PDO::FETCH_ASSOC);
	}

	public static function retrieveByClipId($clip_id)
	{
		$c = new Criteria();

		$c->add(self::CLIP_ID, $clip_id);
		$c->addDescendingOrderByColumn(self::SCENE_TIME);

		return self::doSelect($c);
	}
} // ScenePeer
