<?php



/**
 * Skeleton subclass for performing query and update operations on the 'source' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Mon Feb  6 03:06:04 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SourcePeer extends BaseSourcePeer {

	public static function retrieveByName($name)
	{
		$c = new Criteria();
		$c->clearSelectColumns();
		$c->addSelectColumn(self::ID);
		$c->add(self::NAME, $name);
		$c->setLimit(1);
		return BasePeer::doSelect($c)->fetch(PDO::FETCH_ASSOC);
	}
} // SourcePeer
