<?php



/**
 * Skeleton subclass for performing query and update operations on the 'video' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Thu Feb  2 04:58:14 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class VideoPeer extends BaseVideoPeer {

} // VideoPeer
