generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              sfGuardUser
    plural:                sfGuardUsers
    route_prefix:          sf_guard_user
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   nothing

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:
        class: sfGuardUserFormEmbedOperatorsLst
      edit:    ~
      new:     ~
