generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              sfGuardUser
    plural:                sfGuardUsers
    route_prefix:          sf_guard_user
    with_propel_route:     1
    actions_base_class:    sfActions
    css:                   nothing

    config:
      actions:
        refresh_avatar:
          name: 'Обновить кадр'
          action: refreshAvatar
      fields:  ~
      list:
        sort: [id, desc]
      filter:  ~
      form:    ~
      edit:
        actions:
          _delete: ~
          _list: ~
          _save: ~
          refresh_avatar: ~
      new:     ~
