propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  sf_guard_user_profile:
    sf_guard_user_id: { type: INTEGER, required: true, foreignTable: sf_guard_user, primaryKey: true, sequence: sf_guard_user_id_seq, foreignReference: id }
    first_name: { type: VARCHAR, size: '128', required: false }
    last_name: { type: VARCHAR, size: '128', required: false }
    nick: { type: VARCHAR, size: '64', required: true }
  ext_profile:
    id: ~
    created_at: ~
    sf_guard_user_profile_id: { type: INTEGER, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    ext_id: { type: VARCHAR, size: '64', required: true }
    ext_link: { type: VARCHAR, size: '128', required: true }
    provider: {type: INTEGER, required: true, size: '2'}
  board:
    id: ~
    is_public: { type: BOOLEAN, required: true }
    name: { type: VARCHAR, size: '128', required: true }
    sf_guard_user_profile_id: { type: INTEGER, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    category_id: { type: INTEGER, required: true, foreignTable: category, foreignReference: id }
  category:
    id: ~
    name: { type: VARCHAR, size: '128', required: true }
  clip:
    id: ~
    source_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: source, foreignReference: id }
    name: { type: VARCHAR, size: '128', required: true }
    url: { type: VARCHAR, required: true }
  follower:
    left_sf_guard_user_profile_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    right_sf_guard_user_profile_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
  scene:
    id: ~
    created_at: ~
    clip_id: { type: INTEGER, required: true }
    sf_guard_user_profile_id: { type: INTEGER, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    scene_time: { type: INTEGER, required: true }
    origin_board_id: { type: INTEGER, required: true, foreignTable: board, foreignReference: id }
    has_images: { type: BOOLEAN, required: true }
  scene_like:
    like_sf_guard_user_profile_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    scene_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: scene, foreignReference: id }
  scene_repost:
    scene_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: scene, foreignReference: id }
    board_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: board, foreignReference: id }
  source:
    id: ~
    name: {type: VARCHAR, size: '128', required: false }
  comment:
    _attributes: {phpName: ClipComment}
    id: ~
    sf_guard_user_profile_id: { type: INTEGER, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    scene_id: { type: INTEGER, required: true, foreignTable: scene, foreignReference: id }
    text: { type: LONGVARCHAR, required: true }
  history:
    id: ~
    created_at: ~
    sf_guard_user_profile_id: { type: INTEGER, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    scene_id: { type: INTEGER, required: false, foreignTable: scene, foreignReference: id }
    board_id: { type: INTEGER, required: false, foreignTable: board, foreignReference: id }
    comment_id: { type: INTEGER, required: false, foreignTable: comment, foreignReference: id }
    follower_sf_guard_user_profile_id: { type: INTEGER, required: false, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    follow_sf_guard_user_profile_id: { type: INTEGER, required: false, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }