propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  sf_guard_user_profile:
    sf_guard_user_id: { type: INTEGER, required: true, foreignTable: sf_guard_user, primaryKey: true, sequence: sf_guard_user_id_seq, foreignReference: id }
    first_name: { type: VARCHAR, size: '128', required: false }
    last_name: { type: VARCHAR, size: '128', required: false }
    nick: { type: VARCHAR, size: '64', required: true }
    city: { type: VARCHAR, size: '64', required: false }
    country: { type: VARCHAR, size: '64', required: false }
    gender: { type: BOOLEAN, required: true, default: true }
  ext_profile:
    id: ~
    created_at: { type: timestamp, required: true, defaultExpr: 'now()'}
    sf_guard_user_profile_id: { type: INTEGER, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    ext_id: { type: VARCHAR, size: '64', required: true }
    ext_link: { type: VARCHAR, size: '128', required: true }
    provider: {type: INTEGER, required: true}
  board_refs_category:
    board_id:  { type: INTEGER, required: true, foreignTable: board, primaryKey: true, foreignReference: id }
    category_id: { type: INTEGER, required: true, foreignTable: category, primaryKey: true, foreignReference: id }
    votes: { type: INTEGER, required: true, default: 1 }
  board_refs_user_votes:
    board_id:  { type: INTEGER, required: true, foreignTable: board, primaryKey: true, foreignReference: id }
    sf_guard_user_profile_id: { type: INTEGER, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
  invites:
    created_at: ~
    sf_guard_user_profile_id: { type: INTEGER, required: true, primaryKey: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    ext_id: { type: VARCHAR, size: '80', required: true, primaryKey: true }
  board:
    _propel_behaviors:
      archivable: {archive_on_delete: true, log_archived_at: true}
    id: ~
    is_public: { type: BOOLEAN, required: true, default: true }
    name: { type: VARCHAR, size: '128', required: true }
    sf_guard_user_profile_id: { type: INTEGER, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
  category:
    id: ~
    name: { type: VARCHAR, size: '128', required: true }
  clip:
    _propel_behaviors:
      archivable: {archive_on_delete: true, log_archived_at: true}
    id: ~
    source_id: { type: INTEGER, required: true, foreignTable: source, foreignReference: id }
    name: { type: VARCHAR, size: '128', required: true }
    url: { type: VARCHAR, required: true }
    hide: { type: BOOLEAN, required: true, default: 'false' }
    duration: {type: INTEGER, required: true, default: '0'}
  user_follower:
    following_sf_guard_user_profile_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    follower_sf_guard_user_profile_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    created_at: { type: timestamp, required: true, defaultExpr: 'now()'}
  fb_user_follower:
    following_fb_user_id: { type: VARCHAR, required: true, primaryKey: true }
    follower_sf_guard_user_profile_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    created_at: { type: timestamp, required: true, defaultExpr: 'now()'}
  scene:
    _propel_behaviors:
      archivable: {archive_on_delete: true, log_archived_at: true}
    id: ~
    created_at: { type: timestamp, required: true, defaultExpr: 'now()'}
    scene_time_id: { type: INTEGER, required: true, foreignTable: scene_time, foreignReference: id }
    sf_guard_user_profile_id: { type: INTEGER, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    board_id: { type: INTEGER, required: true, foreignTable: board, foreignReference: id }
    repin_origin_scene_id: { type: INTEGER, required: false, foreignTable: scene, foreignReference: id }
    text: { type: LONGVARCHAR, required: true }
    ext_id: { type: VARCHAR, size: '64', required: false}
  scene_time:
    _propel_behaviors:
      archivable: {archive_on_delete: true, log_archived_at: true}
    id: ~
    reclip_id: { type: INTEGER, required: true, foreignTable: reclip, foreignReference: id }
    scene_time: { type: decimal, required: true }
    created_at: { type: timestamp, required: true, defaultExpr: 'now()'}
    unique_comments_count: { type: INTEGER, required: true, default: '0' }
    _uniques:
      scene_time_id_key: [reclip_id, scene_time]
  reclip:
    _propel_behaviors:
      archivable: {archive_on_delete: true, log_archived_at: true}
    id: ~
    sf_guard_user_profile_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    fb_user_id: { type: VARCHAR, required: false }
    fb_post_id: { type: VARCHAR, required: false }
    clip_id: { type: INTEGER, required: true, foreignTable: clip, foreignReference: id }
    _uniques:
      reclip_id_key: [id]
  scene_like:
    _propel_behaviors:
      archivable: {archive_on_delete: true, log_archived_at: true}
    like_sf_guard_user_profile_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    scene_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: scene, foreignReference: id }
    created_at: { type: timestamp, required: true, defaultExpr: 'now()'}
  scene_repin:
    _propel_behaviors:
      archivable: {archive_on_delete: true, log_archived_at: true}
    repin_sf_guard_user_profile_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    scene_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: scene, foreignReference: id }
    created_at: { type: timestamp, required: true, defaultExpr: 'now()'}
  source:
    id: ~
    name: {type: VARCHAR, size: '128', required: false }
  comment:
    _propel_behaviors:
      archivable: {archive_on_delete: true, log_archived_at: true}
    _attributes: {phpName: SceneComment}
    id: ~
    created_at: { type: timestamp, required: true, defaultExpr: 'now()'}
    reply_to_comment_id: { type: INTEGER, required: false, foreignTable: comment, foreignReference: id }
    sf_guard_user_profile_id: { type: INTEGER, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    scene_time_id: { type: INTEGER, required: true, foreignTable: scene_time, foreignReference: id }
    text: { type: LONGVARCHAR, required: true }
    rating: { type: INTEGER, required: true, default: '0' }
    rating_votes_count: { type: INTEGER, required: true, default: '0' }
  comment_rating_votes:
    _attributes: {phpName: SceneCommentRatingVotes}
    sf_guard_user_profile_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    comment_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: comment, foreignReference: id }
    sign: { type: BOOLEAN, required: true }
  history:
    id: ~
    created_at: { type: timestamp, required: true, defaultExpr: 'now()'}
    sf_guard_user_profile_id: { type: INTEGER, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    event_type: { type: INTEGER, required: true }
    scene_id: { type: INTEGER, required: false, foreignTable: scene, foreignReference: id }
    board_id: { type: INTEGER, required: false, foreignTable: board, foreignReference: id }
    comment_id: { type: INTEGER, required: false, foreignTable: comment, foreignReference: id }
    follow_of_sf_guard_user_profile_id: { type: INTEGER, required: false, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    repin_of_sf_guard_user_profile_id: { type: INTEGER, required: false, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
  clip_follower:
    _propel_behaviors:
      archivable: {archive_on_delete: true, log_archived_at: true}
    clip_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: clip, foreignReference: id }
    follower_sf_guard_user_profile_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    created_at: { type: timestamp, required: true, defaultExpr: 'now()'}
  board_follower:
    _propel_behaviors:
      archivable: {archive_on_delete: true, log_archived_at: true}
    board_id: { type: INTEGER, primaryKey: true, required: false, foreignTable: board, foreignReference: id }
    follower_sf_guard_user_profile_id: { type: INTEGER, primaryKey: true, required: true, foreignTable: sf_guard_user_profile, foreignReference: sf_guard_user_id }
    created_at: { type: timestamp, required: true, defaultExpr: 'now()'}